### ISSUE TITLE
No longer works after Home Assistant update (Home Assistant Core 2022.5.3)

### ISSUE THREAD

**Issue by siebert** [sibbl/kindle-dynamic-screensaver#14]
The screensaver worked fine for me for a long time, but it stopped after I updated Home Assistant and now I get the following error:

```
> kindle-dynamic-screensaver@1.0.2 start /app
> node app.js

Node app is running at localhost:5000
Failed to retrieve content: TypeError: Cannot read property 'map' of undefined
TypeError: Cannot read property 'state' of undefined
    at Cover.render (/app/views/cover.jsx:34:64)
    at processChild (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3134:18)
    at resolve (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:2960:5)
    at ReactDOMServerRenderer.render (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3435:22)
    at ReactDOMServerRenderer.read (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at Object.renderToStaticMarkup (/app/node_modules/react-dom/cjs/react-dom-server.node.development.js:4004:27)
    at View.renderFile [as engine] (/app/node_modules/express-react-views/index.js:69:32)
    at View.render (/app/node_modules/express/lib/view.js:135:8)
    at tryRender (/app/node_modules/express/lib/application.js:640:10)
    at Function.render (/app/node_modules/express/lib/application.js:592:3)
Error: ENOENT: no such file or directory, stat '/app/cover.png'
```

**Comment by sibbl** [comment]
Hi @siebert, thanks for the report.

It looks like your temperature entity doesn't have a state. Maybe some entity name changed in HA after an update?

Unfortunately I also need to say that I don't support this repo anymore. Instead of rendering some custom React app like I did in this project, I moved forward to simply render a Lovelace view. The main reason was that anyone can configure themselves in HA what's shown and have full support of Lovelace components. Maybe this might be a good successor for you? https://github.com/sibbl/hass-lovelace-kindle-screensaver


You might just have to switch the Docker container and point your Kindle to another URL where it fetches the image.
